apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
        - name: web-node
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
            requests:
              memory: "32Mi"
