apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: default
  annotations:
    # Tells cert-manager to automatically use our cluster issuer for this ingress
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    # Forces Traefik to redirect all non-secure HTTP requests to HTTPS
    traefik.ingress.kubernetes.io/router.middlewares: "traefik-redirectscheme@kuberdns"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - akhavanpour.com
    - www.akhavanpour.com
    secretName: akhavanpour-com-tls
  rules:
  - host: akhavanpour.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
  - host: www.akhavanpour.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80

